### ISSUE TITLE
Moderation support

### ISSUE THREAD

**Issue by rixx** [pretalx/pretalx#197]
This is an issue that is well-suited for external contributors – let me know if I can be of any help, either via this issue or via support@pretalx.com.

## What this is about

This issue explores features required to build a great on-site moderation support, as pretalx currently has no moderator mode. There are two big user facing features we'd need, and some technical considerations regarding access control and usability. Thanks go to @MacLemon for his ideas and thoughts that provided major parts of this issue.

#### 1. Cue cards

Cue cards are printed cards, typically ~A5 (landscape) sized that are used by moderators as a support providing information on the talk, the speakers, and surrounding logistics. As place is limited, it is very important to present information well-structured and supportive of moderators needing to gain an overview quickly.

Required information:
- [ ] Title
- [ ] Description
- [ ] Speakers
- [ ] short biographies
- [ ] Talk language
- [ ] Talk length
- [ ] Start, end, room

Optional information:
- [ ] Additional notes added by orga?
- [ ] Concurrent talks
- [ ] Space for notes, if we can manage
- [ ] Previous and upcoming talks in the same room
- [ ] Last time this talk/slot was moved around and previous time/location

It should be possible to print only moderator cards for one day/room. Another important feature would be to re-print **changed** slots after a schedule update. Bonus points for sensible use of colors, and maybe printing the event logo on the icons.

#### 2. Moderator view

The same features should be accessible on a mobile (tablet!) friendly view. To avoid needless user accounts, we should probably make this feature accessible via an  in-URL secret which could be distributed via QR codes. Room specific QR codes would be even more helpful to the moderators.

## Layout drafts

tbd.

## How to get started

First of all, leave a comment on this issue to make sure nobody else starts working on this issue at the same time!

Next, you need pretalx running locally on your machine. First, [fork](https://github.com/pretalx/pretalx/fork) the repository to your own GitHub account. Then clone it locally (or [set it as your remote](https://help.github.com/articles/configuring-a-remote-for-a-fork/) if you already cloned it earlier)

Follow the [developer setup guide](https://docs.pretalx.org/en/latest/developer/setup.html), and then play around with pretalx a bit.
Have a look at the places impacting this issue. Look at the code responsible for the issues (searching for relevant words or files should help you find your way around). We have an explanation of our [code structure](https://docs.pretalx.org/en/latest/developer/concepts.html) and the actual [data models](https://docs.pretalx.org/en/latest/developer/interfaces/models.html).

## How to do this

Look at the cards we provide for printing in `pretalx/orga/views/cards.py` – moderation support should work similarly, and might be even easier, since all cards will be the same size.

## Submit the PR

There are a number of tutorials on the Pull Request workflow online, for example this [short version](https://guides.github.com/introduction/flow/) by GitHub itself and this [more in-depth tutorial](https://www.digitalocean.com/community/tutorials/how-to-create-a-pull-request-on-github).

Remember to provide documentation and tests, if applicable. Run the tests before opening your PR, including style checks. We have a [contribution guide](https://docs.pretalx.org/en/latest/developer/contributing.html), which ought to prove helpful at this stage.

**Comment by luto** [comment]
The "print cards" feature in the schedule editor handles most of the cue cards, but doesn't really stick to the list of attributes above. I reworded it a bit and checked what has been completed so far.

**Comment by rixx** [comment]
No, the printed cards are exclusively for scheduling, and neither their sizing nor their composition is fit for moderation.

**Comment by Astranox** [comment]
As we've used the printed cards again for the pw18 and managed to cut through a few again we'd have some more ideas which would be great to have.
Ideas are based on the "Schedule puzzle"/"Printed cards"

- [ ] include day on the cue card (important for multi-day-events)
- [ ] don't shorten the description, if there is space left
- [ ] show some icons if any of the flags in "can be streamed" or "can be recorded" are set

as the current version looks like some printable version of the schedule:
it might be good to to have the qr-code point to the entry in the public schedule, that regular visitors can use them, instead of pointing to the talk in the restricted area

**Comment by rixx** [comment]
> as the current version looks like some printable version of the schedule:
it might be good to to have the qr-code point to the entry in the public schedule, that regular visitors can use them, instead of pointing to the talk in the restricted area

The current printed cards are meant exclusively for scheduling, and neither their sizing nor their composition is fit for moderation. The printed cards will not be adjusted to be better used as moderation cards. The scheduling link, for example, can't be replaced as it is useful during the scheduling process.

I'm sure whoever implements this feature in the end will keep your other points in mind, though. (Although I'm tempted to declare this a plugin feature, not a core feature.)

**Comment by MacLemon** [comment]
The scheduling cards are hardly usable for scheduling on paper since they're different sizes. Cutting them takes a very long time, or you end up with the aforementioned puzzles of cut-in-half cards. Reprinting that single card is possible, but requires you to have a saved PDF of the cards and finding the corresponding page to reprint.

In the end we tossed the whole stack, and did scheduling in team on the projector.

I can many benefits of paper over the driver-on-the-projector approach though. Here's an idea on how to improve the scheduling cards.


All cutting marks must align across all pages of a printed stash so I can put in the stash of printed scheduling cards into a paper cutter and efficiently cut the whole stash to size.

![How to possibly improve scheduling cards](https://user-images.githubusercontent.com/90635/72448522-70d87c00-37b7-11ea-8396-d18b0219741b.png)

## Example for current, unaligned scheduling cards:
- 10 Pages printed
- align 10 pages into paper cutter, make cut along the long center line
- align first of the 20 paper slips and cut between the cards, about 3 cuts per slip.
Total 61 cuts to make sure you don't get any miscut cards. (At 4 seconds per cut, plus half a minute preparation and taking care you don't cut your fingers that process takes almost 5 minutes.)

Pro: Feature already exists, nothing to do.
Con: Annoying to use, error prone

## Example for improved same-size aligned cards:
- 10 pages printed
- align 10 pages into paper cutter, make cut along the long center line
-  align all 20 paper slips and cut between the cards, 3 cuts in total.
Total: 4 cuts, can be done in under 2 minutes.

Pro: easier, faster card cutting action, less cut fingers
Con: talk duration / slot gutter not necessarily represented by card size.


# Ultimate scheduling cards
- Convey talk length by size/length of card (at the cost of necessarily having to cut off some abstracts to match the size, or risk very tiny, hence unreadable print.)
- Equal length talks are aligned on cards, so the cutting marks align for the whole stack
- Best of both worlds, joy and happiness ensues!

Cons: Layouting is harder.

**Comment by Gailogail** [comment]
PyCon UK (and hopefully others!) would like a 'countdown timer' tied to the schedule, to help session chairs. Anyone - moderator, speaker, audience - would be able to access a view for the session they're attending which shows exactly when it should start and fully finish, counting down the minutes as the elapse. Would that be an addition to this moderation support issue, or a separate one?

**Comment by rixx** [comment]
I think that's covered by #791. I'm happy to support anybody starting on a PR for this, but I don't currently have the capacity to prioritise it.

**Comment by Gailogail** [comment]
Great, thank you. I only needed the right place to put it. Now I have that I am going to see if I can enlist help to implement it :-)

**Comment by rixx** [comment]
This issue was closed while we were test driving GitHub Discussions for feature ideas, re-opened for further consideration.

Just linking Kunsi/pretalx-plugin-broadcast-tools#10 real quick, since that's roughly what cue cards / moderation cards would look like, with some fancy cool features like metadata on the left margin to facilitate sorting/finding, nice layouts, and more. There are some things I'd like to add or change (empty fields for pronouns and/or name pronunciation guide, to encourage moderators to get those ahead of time, maybe another notes field with boxes for "takes questions", or customisable boxes defined by organisers). But those are details, and having something like that PR in pretalx-core would be an extremely good first step. Maybe even before the 3.0 release?
