### ISSUE TITLE
Social media integration

### ISSUE THREAD

**Issue by rixx** [pretalx/pretalx#201]
Twitter integration spans a variety of features and settings, to be explained below. The aim of twitter integration is to provide features like scheduled tweets, share buttons (privacy friendly ones, naturally), etc.

### Required settings
- [ ] Enable twitter integration: true/**false**, global setting enabling/disabling the other settings
- [ ] Show "share on twitter" buttons: **true**/false
- [ ] Twitter nick and hashtag: This is required for better sharing integration
- [ ] Send tweets when talks start: true/**false**
- [ ] Talk-tweeter template: string with placeholders and a defined order in which the placeholders are dropped. Since this is kinda hard, we might have to stick with just a language selection for now.
- [ ] Send tweets when a new schedule version is released: true/**false**
- [ ] Twitter credentials for scheduled tweets: an account and access codes will need to be stored if scheduled tweets are used
- [ ] Ask speakers for twitter username: true/**false**
- [ ] Offer submitters to tweet "I have just submitted a talk to": **true**/false
- [ ] Tweet other special events (CfP countdown on days 7, 1, 0.5, 0; CfP open, Event end). It might be best to provide editable templates for this, aswell.
- [ ] Tweet schedule changes

### Feature explanations

Every part of the twitter integration should be opt-in, naturally, but at the same time we want to offer as many features as we can.

### Technical considerations

Scheduled tweets implies a timing of some sort. This should also be made transparent (i.e.: when is the next tweet going to go out, aswell as a visible history of sent tweets from pretalx' point of view).

**Comment by MacLemon** [comment]
Also make it *toot*!
Provide call-hooks for these events for plugins or (shell) scripts to tie into this notification system?

**Comment by rixx** [comment]
Twitter integration will not land in pretalx-core now that we have a proper plugin system. My current plans involve implementing an open source Mastodon plugin for pretalx, publishing a **console script** that sends tweets when fed a schedule.xml export, and building a Twitter **plugin** that will be available on hosted pretalx.

**Comment by rixx** [comment]
We're moving all plugin ideas from the issue tracker to [this page](https://github.com/pretalx/pretalx/wiki/Plugin-ideas/).
