### ISSUE TITLE
Support tracks

### ISSUE THREAD

**Issue by rixx** [pretalx/pretalx#234]
Now, tracks are a difficult topic, as people mean different concepts when talking about tracks. Tracks are, at their core, a label describing a topic, which may be connected to talks. Beyond that, there are a couple of things to note:

- Tracks may be bound to a day
- Tracks may be bound to a room
- Just because one track is bound to a day or room, not all other tracks have to be bound aswell
- Some conferences prefer that each talk belong to one track, others use tracks more in line with a tagging system.

- [x] Implement data structure (incl permissions, serialization, …)
- [x] Implement sensible settings
- [x] Build a good schedule display

**Comment by rixx** [comment]
We could implement a tagging system *in addition* to tracks.
