### ISSUE TITLE
Add a read-only REST API

### ISSUE THREAD

**Issue by rixx** [pretalx/pretalx#268]
I'm imagining the following endpoints and features:

- [x] `/events` (and `/event/<slug>`)
- [x] `/events/<slug>/submissions/` (and `talks` for a pre-filtered list, and `…/<code>/` for detail views, with talk slots if available), plus filtering
- [ ] `/events/<slug>/submitters/` (and `speakers` for a pre-filtered list, and `…/<code>/` for detail views), plus filtering
- [x] `/events/<slug>/schedules`
- [ ] `/events/<slug>/schedules/latest/` with all talk slots in the current schedule
- [ ] The API needs to have a path behind a `/v1/` subpath
- [x] API documentation
- [x] Heavy integration of permissions, since parts of the API are shown to unauthenitcated users
- [x] Heavy testing
