### ISSUE TITLE
Follow accessibility guidelines

### ISSUE THREAD

**Issue by rixx** [pretalx/pretalx#332]
We should take care to follow the [W3C accessibility guidelines](https://www.w3.org/TR/WCAG/).

- [x] Perceiving
  - [x] [Provide alternatives/descriptions for non-text content](https://www.w3.org/TR/WCAG/#non-text-content)
  - [x] [Use appropriate contrast, and make sure user-defined colors do so, too](https://www.w3.org/TR/WCAG/#contrast-minimum). [Follow the enhances spec](https://www.w3.org/TR/WCAG/#contrast-enhanced)
  - [x] [Resizing pretalx works well](https://www.w3.org/TR/WCAG/#resize-text)
  - [x] [Make visual presentation of text customizable](https://www.w3.org/TR/WCAG/#visual-presentation)
  - [x] [Work well with small/zoomed in displays](https://www.w3.org/TR/WCAG/#reflow)
  - [x] [Ensure good contrast in non-text components](https://www.w3.org/TR/WCAG/#non-text-contrast)
  - [x] [Look at text spacing](https://www.w3.org/TR/WCAG/#text-spacing)
  - [ ] [Look at hover interaction](https://www.w3.org/TR/WCAG/#content-on-hover-or-focus)
- [x] Operating
  - [x] [Make pretalx usable via keyboard](https://www.w3.org/TR/WCAG/#keyboard-accessible)
  - [x] [Fix the pretalx title attribute](https://www.w3.org/TR/WCAG/#page-titled)
  - [x] [Always provide the purpose of a link](https://www.w3.org/TR/WCAG/#link-purpose-in-context), and if possible [in the link alone](https://www.w3.org/TR/WCAG/#link-purpose-link-only)
  - [x] [Provide deacivation and remapping of keyboard shortcuts](https://www.w3.org/TR/WCAG/#character-key-shortcuts)
  - [x] [Provide sufficiently sized targets for pointer inputs](https://www.w3.org/TR/WCAG/#target-size)
  - [x] [Work well with portrait or landscape mode](https://www.w3.org/TR/WCAG/#orientation)
- [x] Understanding
  - [x] [Explain on-input behaviour in schedule editor](https://www.w3.org/TR/WCAG/#on-input)
  - [x] [Provide explicit instructions when requiring input](https://www.w3.org/TR/WCAG/#labels-or-instructions). This might be relevant to availability input
  - [ ] [Provide error suggestions](https://www.w3.org/TR/WCAG/#error-suggestion)
  - [ ] [Provide context sensitive help](https://www.w3.org/TR/WCAG/#help)

This is an issue that is well-suited for external contributors – let me know if I can be of any help, either via this issue or via support@pretalx.com.

## How to get started

You'll need pretalx running locally on your machine. First, [fork](https://github.com/pretalx/pretalx/fork) the repository to your own GitHub account. Then clone it locally (or [set it as your remote](https://help.github.com/articles/configuring-a-remote-for-a-fork/) if you already cloned it earlier)

Follow the [developer setup guide](https://docs.pretalx.org/en/latest/developer/setup.html), and then play around with pretalx a bit.
Have a look at the places impacting this issue. Look at the code responsible for the issues (searching for relevant words or files should help you find your way around). We have an explanation of our [code structure](https://docs.pretalx.org/en/latest/developer/concepts.html) and the actual [data models](https://docs.pretalx.org/en/latest/developer/interfaces/models.html).

## How to do this

Choose one or a few points of the checklist above. Check on as many relevant pretalx pages as possible if the points you've chosen are implemented or not. If not, make the changes required (most likely in some `…/templates/….html` files and submit a PR. If you find that pretalx already covers a point, leava comment so that we can cross it off the list.

## Submit the PR

There are a number of tutorials on the Pull Request workflow online, for example this [short version](https://guides.github.com/introduction/flow/) by GitHub itself and this [more in-depth tutorial](https://www.digitalocean.com/community/tutorials/how-to-create-a-pull-request-on-github).

Remember to provide documentation and tests, if applicable. Run the tests before opening your PR, including style checks. We have a [contribution guide](https://docs.pretalx.org/en/latest/developer/contributing.html), which ought to prove helpful at this stage.

**Comment by rixx** [comment]
I'll close this issue because the easy pickings are done. If or when additional accessibility issues crop up, we can handle them in separate issues.
