### ISSUE TITLE
Event design help and guide

### ISSUE THREAD

**Issue by rixx** [pretalx/pretalx#391]
pretalx currently is not very helpful towards designers. We should at the very least do the following:

- [ ] Settle on preferred logo dimensions and put them in the help text (dimensions, file type, resolution)
- [ ] Write a design guide (part of the user guide documentation)
   - [ ] Add custom colors
   - [ ] Add logo dimensions
   - [ ] Link in all places that require or allow pretalx customisation
- [ ] Add a preview when modifying logo/color
- [ ] Render custom header preview with custom color
- [ ] Mention important colors and variables to change
- [ ] Provide an example file changing agenda width and some colors (success/error for example)
- [ ] Provide image help (dimensions, file type, where it'll be displayed) in submission form for speakers

**Comment by rixx** [comment]
This should be part of the user documentation. #397
