### ISSUE TITLE
Add ical export

### ISSUE THREAD

**Issue by rixx** [pretalx/pretalx#67]
- [x] Add ical export for single event
- [x] Add ical export for all events
- [x] Add ical export for all events of a speaker: https://github.com/pretalx/pretalx/pull/304
- [x] Add ical url for single event
- [x] Add ical url for all events
- [ ] Add ical export for group of events
- [ ] Add ical url for group of events
- [ ] Add UI mode to define a group of events

**Comment by rixx** [comment]
This, of course, needs a lot of UI considerations – I'm not really sure how you'd switch to that mode and back again, except via a button in the export dropdown.
